language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "graceshopper-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: quarantivities
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: gHpcDvAQ7IJoP55qXq39p+TDjjz7eMj4OK1uPlHcBP8Iwh4xPGdon2U3D3nRTzUQ3Vw38ZexcR1VRtiihDm/XdrHx44wymfTdCNPjkVxQzsIGKKavJ8bA/fPiSWlfkx29+DEiGXxoz3FN7q1zb/NHtdKl/B94VwpCy0+Gp8aceDDDurhru/Gnk3agfBHihpULEwy8B9i1zY73RG5V5fw5aSN14zVdmCMCbrIAFrcvePdOauegx8WIOAr37aztG23WG+93+dAIM4Tv6Z8ES+e/E1gQN+mVTirklvOtLB5sjdwMeFdwstko6EHJmKOTvvzXNUVUedd1o5NpA3llO99pjazq3QC78/TdCrCK6Y3NGsh4dT0Wv1XB06xNgjJefyzFyTBD0/QjL6KiQuvC6kToNQMRLHmHZdAB3vSaZx4G1W+dWhUZx2QgxMrWq7/6C3a4RyColJusnI5uL3+89vJfXrTC2GjJ1QJzDtECHakLhpi5ahmWdeFtMNkjP5r5cpGNGNtTQgxqYIB1VpIvn40kba8dPxZbdJy/OYJEDvDSZB0K3t/gVKu52PE9qIhrMf0yCE85SWxi3SJFmNW2sb5QUawT8ugJuGQuWPydDIDQpDprlmuoic+jzkfGT76+QWWscs6r57d2QdDk5EejjvjSe0M5pEO1WHn5u5wPuwn+FY=
